version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./backend/tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  server:
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/backend
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
  client:
    build: ./frontend
    command: sh -c "yarn install && yarn start"
    volumes:
      - ./frontend:/frontend
    ports:
      - '3001:3001'
      - '3002:3002'
    tty: true
